# Generated by Django 4.1.5 on 2023-02-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="varient",
            new_name="variant",
        ),
    ]
