# Generated by Django 4.1.5 on 2023-01-24 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="product_varient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="product.variation",
                verbose_name="Product Varient",
            ),
        ),
    ]
