# Generated by Django 4.1.5 on 2023-01-25 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_variation_is_default"),
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="product_varient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_inventory",
                to="product.variation",
                verbose_name="Product Varient",
            ),
        ),
    ]
