# Generated by Django 4.1.5 on 2023-01-24 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0002_rename_desciption_campaign_description"),
        ("order", "0002_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="order_discount",
                to="campaign.campaign",
            ),
        ),
    ]
