# Generated by Django 4.1.5 on 2023-02-14 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitemserializer",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_item",
                to="order.order",
            ),
            preserve_default=False,
        ),
    ]
