# Generated by Django 4.1.5 on 2023-02-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_orderitem_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="product",
            new_name="variant",
        ),
    ]
