# Generated by Django 4.1.5 on 2023-02-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
        ("campaign", "0001_initial"),
        ("order", "0003_orderitemserializer_order"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderItemSerializer",
            new_name="OrderItem",
        ),
    ]
