# Generated by Django 4.1.5 on 2023-02-14 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0001_initial"),
        ("order", "0004_rename_orderitemserializer_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="order_item",
                to="campaign.campaign",
            ),
        ),
    ]
