# Generated by Django 4.1.5 on 2023-02-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_remove_orderitem_campaign_orderitem_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="promocode_applied",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
