# Generated by Django 4.1.5 on 2023-02-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_alter_orderitem_campaign"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="discount_percent",
        ),
    ]
