# Generated by Django 4.1.5 on 2023-02-09 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0004_alter_campaign_discount"),
        ("order", "0006_orderitem_promocode_applied"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="promocode_applied",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="order_item",
                to="campaign.campaign",
            ),
            preserve_default=False,
        ),
    ]
