# Generated by Django 4.1.5 on 2023-02-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_remove_orderitem_discount_percent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="initial_price",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
