# Generated by Django 4.1.5 on 2023-02-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_remove_orderitem_initial_price_orderitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "ORDER CREATED"),
                    ("PLACED", "ORDER PLACED"),
                    ("APPROVED", "ORDER APPROVED"),
                    ("REJECTED", "ORDER REJECTED"),
                    ("SHIPPED", "ORDER SHIPPED"),
                    ("DELIVERED", "ORDER DELIVERED"),
                ],
                default="CREATED",
                max_length=32,
            ),
        ),
    ]
