# Generated by Django 4.1.5 on 2023-02-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_alter_orderitem_promocode_applied"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="promocode_applied",
            new_name="campaign",
        ),
    ]
