# Generated by Django 4.1.5 on 2023-02-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_rename_promocode_applied_orderitem_campaign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="campaign",
            field=models.JSONField(),
        ),
    ]
