# Generated by Django 4.1.5 on 2023-02-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_alter_orderitem_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_items",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
