# Generated by Django 4.1.5 on 2023-02-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_order_order_items_delete_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
