# Generated by Django 4.1.5 on 2023-02-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0012_alter_order_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD")], default="USD", max_length=3
            ),
        ),
    ]
