# Generated by Django 4.1.5 on 2023-01-25 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_variation_is_default"),
        ("cart", "0002_alter_cartitem_campaign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_item",
                to="product.variation",
            ),
        ),
    ]
