# Generated by Django 4.1.5 on 2023-02-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cart_user_alter_cartitem_campaign_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="product",
            new_name="variant",
        ),
    ]
