# Generated by Django 4.1.5 on 2023-02-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_rename_product_cartitem_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
