# Generated by Django 4.1.5 on 2023-02-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_productvariant_sku"),
        ("campaign", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="product",
            field=models.ManyToManyField(related_name="campaign", to="product.product"),
        ),
    ]
