# Generated by Django 4.1.5 on 2023-01-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("campaign", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="product",
            field=models.ManyToManyField(
                related_name="product_promotion", to="product.product"
            ),
        ),
    ]
