# Generated by Django 4.1.5 on 2023-02-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0002_alter_campaign_promocode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="promocode",
            field=models.CharField(max_length=16),
        ),
    ]
