# Generated by Django 4.1.5 on 2023-02-08 14:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0003_alter_campaign_promocode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Value in percentage",
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
