# Generated by Django 4.1.5 on 2023-01-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
    ]
