# Generated by Django 4.1.5 on 2023-02-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["variant__price"]},
        ),
    ]
