# Generated by Django 4.1.5 on 2023-01-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_variation_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD")], default="USD", max_length=3
            ),
        ),
    ]
