# Generated by Django 4.1.5 on 2023-02-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_productvariant_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="is_default",
            field=models.BooleanField(default=True),
        ),
    ]
