# Generated by Django 4.1.5 on 2023-01-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_variation_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("SIZE", "SIZE"), ("COLOUR", "COLOUR")],
                max_length=32,
                null=True,
            ),
        ),
    ]
