# Generated by Django 4.1.5 on 2023-01-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_remove_product_image_remove_product_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Inventory",
        ),
    ]
