# Generated by Django 4.1.5 on 2023-01-23 09:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_variation_quantity_delete_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price in USD",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
