# Generated by Django 4.1.5 on 2023-01-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_variation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="type",
            field=models.CharField(
                choices=[("SIZE", "SIZE"), ("COLOUR", "COLOUR")], max_length=32
            ),
        ),
    ]
