# Generated by Django 4.1.5 on 2023-01-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_variation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
