# Generated by Django 4.1.5 on 2023-01-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_alter_order_user"),
        ("cart", "0003_alter_cartitem_product"),
        ("inventory", "0003_alter_inventory_product_varient"),
        ("product", "0006_variation_is_default"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Variation",
            new_name="ProductVariant",
        ),
    ]
