# Generated by Django 4.1.5 on 2023-01-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_rename_variation_productvariant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="type",
            field=models.CharField(
                choices=[("SIZE", "SIZE"), ("COLOUR", "COLOUR"), ("None", "None")],
                max_length=32,
            ),
        ),
    ]
