# Generated by Django 4.1.5 on 2023-01-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_alter_productvariant_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="type",
            field=models.CharField(
                choices=[("SIZE", "SIZE"), ("COLOUR", "COLOUR"), ("NONE", "NONE")],
                max_length=32,
            ),
        ),
    ]
