# Generated by Django 4.1.5 on 2023-01-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_alter_productvariant_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="type",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="primary_type",
            field=models.CharField(
                choices=[("SIZE", "SIZE"), ("COLOUR", "COLOUR"), ("NONE", "NONE")],
                default="NONE",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="secondary_type",
            field=models.CharField(
                choices=[("SIZE", "SIZE"), ("COLOUR", "COLOUR"), ("NONE", "NONE")],
                default="NONE",
                max_length=32,
            ),
        ),
    ]
