# Generated by Django 4.1.5 on 2023-01-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_remove_productvariant_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productvariant",
            old_name="primary_type",
            new_name="type1",
        ),
        migrations.RenameField(
            model_name="productvariant",
            old_name="secondary_type",
            new_name="type2",
        ),
    ]
