# Generated by Django 4.1.5 on 2023-01-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_rename_primary_type_productvariant_type1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("value", models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="name",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="type1",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="type2",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="attribute",
            field=models.ManyToManyField(
                related_name="product_attribute", to="product.productattribute"
            ),
        ),
    ]
