# Generated by Django 4.1.5 on 2023-01-26 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_productattribute_remove_productvariant_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant",
                to="product.product",
            ),
        ),
    ]
