# Generated by Django 4.1.5 on 2023-01-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_alter_category_options"),
        ("product", "0013_alter_productvariant_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                related_name="product_category", to="category.category"
            ),
        ),
    ]
