# Generated by Django 4.1.5 on 2023-01-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0015_alter_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="productattribute",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="productvariant",
            options={"ordering": ["-is_default", "price"]},
        ),
    ]
