# Generated by Django 4.1.5 on 2023-01-26 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0016_alter_product_options_alter_productattribute_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="attribute",
            field=models.ManyToManyField(
                related_name="product_variants", to="product.productattribute"
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="product.product",
            ),
        ),
    ]
