# Generated by Django 4.1.5 on 2023-02-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_payment_amount_paid_payment_amount_requested"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount_paid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
