# Generated by Django 4.1.5 on 2023-01-23 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_category_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
