# Generated by Django 4.1.5 on 2023-02-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviews",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Reviews",
                "verbose_name_plural": "Reviews",
            },
        ),
    ]
