# Generated by Django 4.1.5 on 2023-03-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False, verbose_name="Email Verified"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_phone_number_verified",
            field=models.BooleanField(
                default=False, verbose_name="Phone Number Verified"
            ),
        ),
    ]
